version: "3.9"

services:

  conx-popup:
    container_name: conx-popup
    build: ./django-backend
    volumes:
      - ./django-backend:/code
    ports:
      - "28000:8000"
  
  # react-app:
  #   container_name: react-app
  #   build: ./reactjs-frontend
  #   command: ["tail", "-f", "/dev/null"]
  #   volumes:
  #     - ./reactjs-frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - NODE_OPTIONS=--openssl-legacy-provider