version: "3.9"

services:

  conx-popup:
    container_name: conx-popup
    build: ./django-backend
    volumes:
      - ./django-backend:/code
    ports:
      - "28000:8000"
  
  react-app:
    container_name: react-app
    build: ./frontend/react-template
    # command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./frontend/react-template:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # create-ui-app <= 5.x
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
      - NODE_OPTIONS=--openssl-legacy-provider