# Generated by Django 4.2.17 on 2025-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='late_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='monthly_payment',
            field=models.IntegerField(default=0),
        ),
    ]
