# Generated by Django 4.2.17 on 2025-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_calloutcome_phoneinfo_productinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneinfo',
            old_name='other_contact_relationship',
            new_name='other_contact_name_2',
        ),
    ]
